// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// base_fit
arma::vec base_fit(double a, double b, const arma::uvec& emp_vec);
RcppExport SEXP _hmod_base_fit(SEXP aSEXP, SEXP bSEXP, SEXP emp_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type emp_vec(emp_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(base_fit(a, b, emp_vec));
    return rcpp_result_gen;
END_RCPP
}
// base_pay_sim
arma::vec base_pay_sim(const arma::vec& base_pay_empirical, int n_sim);
RcppExport SEXP _hmod_base_pay_sim(SEXP base_pay_empiricalSEXP, SEXP n_simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type base_pay_empirical(base_pay_empiricalSEXP);
    Rcpp::traits::input_parameter< int >::type n_sim(n_simSEXP);
    rcpp_result_gen = Rcpp::wrap(base_pay_sim(base_pay_empirical, n_sim));
    return rcpp_result_gen;
END_RCPP
}
// base_pay_sim_beta
arma::vec base_pay_sim_beta(const arma::vec& base_pay_empirical, const arma::vec& beta_empirical, const arma::vec& beta_simulated);
RcppExport SEXP _hmod_base_pay_sim_beta(SEXP base_pay_empiricalSEXP, SEXP beta_empiricalSEXP, SEXP beta_simulatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type base_pay_empirical(base_pay_empiricalSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_empirical(beta_empiricalSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_simulated(beta_simulatedSEXP);
    rcpp_result_gen = Rcpp::wrap(base_pay_sim_beta(base_pay_empirical, beta_empirical, beta_simulated));
    return rcpp_result_gen;
END_RCPP
}
// beta_sim_linear
arma::vec beta_sim_linear(const arma::uvec& employment, const arma::vec& beta, const arma::uvec& sim_employment, double bin_factor);
RcppExport SEXP _hmod_beta_sim_linear(SEXP employmentSEXP, SEXP betaSEXP, SEXP sim_employmentSEXP, SEXP bin_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type employment(employmentSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sim_employment(sim_employmentSEXP);
    Rcpp::traits::input_parameter< double >::type bin_factor(bin_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_sim_linear(employment, beta, sim_employment, bin_factor));
    return rcpp_result_gen;
END_RCPP
}
// beta_sim_log
arma::vec beta_sim_log(const arma::uvec& employment, const arma::vec& beta, const arma::uvec& sim_employment, double bin_factor);
RcppExport SEXP _hmod_beta_sim_log(SEXP employmentSEXP, SEXP betaSEXP, SEXP sim_employmentSEXP, SEXP bin_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type employment(employmentSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sim_employment(sim_employmentSEXP);
    Rcpp::traits::input_parameter< double >::type bin_factor(bin_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_sim_log(employment, beta, sim_employment, bin_factor));
    return rcpp_result_gen;
END_RCPP
}
// boot_mean
arma::vec boot_mean(arma::vec x, double conf, double n_boot);
RcppExport SEXP _hmod_boot_mean(SEXP xSEXP, SEXP confSEXP, SEXP n_bootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type conf(confSEXP);
    Rcpp::traits::input_parameter< double >::type n_boot(n_bootSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_mean(x, conf, n_boot));
    return rcpp_result_gen;
END_RCPP
}
// boot_sigma
double boot_sigma(arma::vec x);
RcppExport SEXP _hmod_boot_sigma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_sigma(x));
    return rcpp_result_gen;
END_RCPP
}
// boot_span
arma::vec boot_span(arma::vec h, arma::vec s);
RcppExport SEXP _hmod_boot_span(SEXP hSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_span(h, s));
    return rcpp_result_gen;
END_RCPP
}
// ceo_pay_ratio
arma::vec ceo_pay_ratio(double a, double b, const arma::vec& base_employment_vec, const arma::uvec& total_employment_vec, const arma::vec& base_pay_vec, const arma::vec& beta_vec);
RcppExport SEXP _hmod_ceo_pay_ratio(SEXP aSEXP, SEXP bSEXP, SEXP base_employment_vecSEXP, SEXP total_employment_vecSEXP, SEXP base_pay_vecSEXP, SEXP beta_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_employment_vec(base_employment_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type total_employment_vec(total_employment_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_pay_vec(base_pay_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_vec(beta_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(ceo_pay_ratio(a, b, base_employment_vec, total_employment_vec, base_pay_vec, beta_vec));
    return rcpp_result_gen;
END_RCPP
}
// firm_grid
arma::imat firm_grid(arma::vec base_vec, int stretch);
RcppExport SEXP _hmod_firm_grid(SEXP base_vecSEXP, SEXP stretchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type base_vec(base_vecSEXP);
    Rcpp::traits::input_parameter< int >::type stretch(stretchSEXP);
    rcpp_result_gen = Rcpp::wrap(firm_grid(base_vec, stretch));
    return rcpp_result_gen;
END_RCPP
}
// firm_mean_pay
arma::vec firm_mean_pay(double a, double b, const arma::vec& base_employment_vec, const arma::uvec& total_employment_vec, const arma::vec& base_pay_vec, const arma::vec& beta_vec);
RcppExport SEXP _hmod_firm_mean_pay(SEXP aSEXP, SEXP bSEXP, SEXP base_employment_vecSEXP, SEXP total_employment_vecSEXP, SEXP base_pay_vecSEXP, SEXP beta_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_employment_vec(base_employment_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type total_employment_vec(total_employment_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_pay_vec(base_pay_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_vec(beta_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(firm_mean_pay(a, b, base_employment_vec, total_employment_vec, base_pay_vec, beta_vec));
    return rcpp_result_gen;
END_RCPP
}
// fit_beta
arma::mat fit_beta(double a, double b, const arma::vec& base_employment_vec, const arma::uvec& total_employment_vec, const arma::vec& ceo_ratio_vec, const arma::vec& firm_mean_pay_vec, double ceo_ratio_error_tolerance, double min_beta, double max_beta);
RcppExport SEXP _hmod_fit_beta(SEXP aSEXP, SEXP bSEXP, SEXP base_employment_vecSEXP, SEXP total_employment_vecSEXP, SEXP ceo_ratio_vecSEXP, SEXP firm_mean_pay_vecSEXP, SEXP ceo_ratio_error_toleranceSEXP, SEXP min_betaSEXP, SEXP max_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_employment_vec(base_employment_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type total_employment_vec(total_employment_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ceo_ratio_vec(ceo_ratio_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type firm_mean_pay_vec(firm_mean_pay_vecSEXP);
    Rcpp::traits::input_parameter< double >::type ceo_ratio_error_tolerance(ceo_ratio_error_toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type min_beta(min_betaSEXP);
    Rcpp::traits::input_parameter< double >::type max_beta(max_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_beta(a, b, base_employment_vec, total_employment_vec, ceo_ratio_vec, firm_mean_pay_vec, ceo_ratio_error_tolerance, min_beta, max_beta));
    return rcpp_result_gen;
END_RCPP
}
// fit_r
arma::mat fit_r(double a, double b, const arma::vec& base_emp_vec, const arma::uvec& emp_vec, const arma::vec& c_r_vec, const arma::vec& m_pay_vec, double tol);
RcppExport SEXP _hmod_fit_r(SEXP aSEXP, SEXP bSEXP, SEXP base_emp_vecSEXP, SEXP emp_vecSEXP, SEXP c_r_vecSEXP, SEXP m_pay_vecSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_emp_vec(base_emp_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type emp_vec(emp_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c_r_vec(c_r_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m_pay_vec(m_pay_vecSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_r(a, b, base_emp_vec, emp_vec, c_r_vec, m_pay_vec, tol));
    return rcpp_result_gen;
END_RCPP
}
// get_data
DataFrame get_data(std::string filename, std::vector<int> ids);
RcppExport SEXP _hmod_get_data(SEXP filenameSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_data(filename, ids));
    return rcpp_result_gen;
END_RCPP
}
// get_ngrams
std::vector<std::string> get_ngrams(std::string filename);
RcppExport SEXP _hmod_get_ngrams(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ngrams(filename));
    return rcpp_result_gen;
END_RCPP
}
// gini
double gini(arma::vec x, bool corr);
RcppExport SEXP _hmod_gini(SEXP xSEXP, SEXP corrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type corr(corrSEXP);
    rcpp_result_gen = Rcpp::wrap(gini(x, corr));
    return rcpp_result_gen;
END_RCPP
}
// grc
double grc(arma::vec n_subordinates);
RcppExport SEXP _hmod_grc(SEXP n_subordinatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type n_subordinates(n_subordinatesSEXP);
    rcpp_result_gen = Rcpp::wrap(grc(n_subordinates));
    return rcpp_result_gen;
END_RCPP
}
// grid_plot_beta
arma::mat grid_plot_beta(double a, double b, double sigma, arma::umat firm_grid, arma::vec emp_vec, arma::vec base_vec, arma::vec base_pay_vec, arma::vec beta_vec);
RcppExport SEXP _hmod_grid_plot_beta(SEXP aSEXP, SEXP bSEXP, SEXP sigmaSEXP, SEXP firm_gridSEXP, SEXP emp_vecSEXP, SEXP base_vecSEXP, SEXP base_pay_vecSEXP, SEXP beta_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type firm_grid(firm_gridSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type emp_vec(emp_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type base_vec(base_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type base_pay_vec(base_pay_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_plot_beta(a, b, sigma, firm_grid, emp_vec, base_vec, base_pay_vec, beta_vec));
    return rcpp_result_gen;
END_RCPP
}
// grid_plot_r
arma::mat grid_plot_r(double a, double b, double sigma, arma::umat firm_grid, arma::vec base_vec, arma::vec base_pay_vec, arma::vec r_vec);
RcppExport SEXP _hmod_grid_plot_r(SEXP aSEXP, SEXP bSEXP, SEXP sigmaSEXP, SEXP firm_gridSEXP, SEXP base_vecSEXP, SEXP base_pay_vecSEXP, SEXP r_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type firm_grid(firm_gridSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type base_vec(base_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type base_pay_vec(base_pay_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r_vec(r_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_plot_r(a, b, sigma, firm_grid, base_vec, base_pay_vec, r_vec));
    return rcpp_result_gen;
END_RCPP
}
// hierarchical_power
arma::vec hierarchical_power(arma::uvec hierarchy_vec);
RcppExport SEXP _hmod_hierarchical_power(SEXP hierarchy_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type hierarchy_vec(hierarchy_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchical_power(hierarchy_vec));
    return rcpp_result_gen;
END_RCPP
}
// hierarchy
arma::vec hierarchy(const double& firm_size, const double& span_of_control);
RcppExport SEXP _hmod_hierarchy(SEXP firm_sizeSEXP, SEXP span_of_controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type firm_size(firm_sizeSEXP);
    Rcpp::traits::input_parameter< const double& >::type span_of_control(span_of_controlSEXP);
    rcpp_result_gen = Rcpp::wrap(hierarchy(firm_size, span_of_control));
    return rcpp_result_gen;
END_RCPP
}
// hp_mod
arma::vec hp_mod(const arma::vec& firm_vec, double span);
RcppExport SEXP _hmod_hp_mod(SEXP firm_vecSEXP, SEXP spanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type firm_vec(firm_vecSEXP);
    Rcpp::traits::input_parameter< double >::type span(spanSEXP);
    rcpp_result_gen = Rcpp::wrap(hp_mod(firm_vec, span));
    return rcpp_result_gen;
END_RCPP
}
// k_function
arma::vec k_function(arma::vec pay, arma::vec power, arma::mat k_parameters);
RcppExport SEXP _hmod_k_function(SEXP paySEXP, SEXP powerSEXP, SEXP k_parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pay(paySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type power(powerSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type k_parameters(k_parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(k_function(pay, power, k_parameters));
    return rcpp_result_gen;
END_RCPP
}
// lorenz
arma::mat lorenz(arma::vec pay, double lower, double upper, int n_bins);
RcppExport SEXP _hmod_lorenz(SEXP paySEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP n_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pay(paySEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(lorenz(pay, lower, upper, n_bins));
    return rcpp_result_gen;
END_RCPP
}
// lotka_volt
arma::mat lotka_volt(double r_0, double c_0, double k_1, double k_2, double k_3, double time, double step_size);
RcppExport SEXP _hmod_lotka_volt(SEXP r_0SEXP, SEXP c_0SEXP, SEXP k_1SEXP, SEXP k_2SEXP, SEXP k_3SEXP, SEXP timeSEXP, SEXP step_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type r_0(r_0SEXP);
    Rcpp::traits::input_parameter< double >::type c_0(c_0SEXP);
    Rcpp::traits::input_parameter< double >::type k_1(k_1SEXP);
    Rcpp::traits::input_parameter< double >::type k_2(k_2SEXP);
    Rcpp::traits::input_parameter< double >::type k_3(k_3SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lotka_volt(r_0, c_0, k_1, k_2, k_3, time, step_size));
    return rcpp_result_gen;
END_RCPP
}
// lotka_volt_cumulative
arma::mat lotka_volt_cumulative(double r_0, double c_0, double k_1, double k_2, double k_3_init, double k_3_slope, double time, double step_size);
RcppExport SEXP _hmod_lotka_volt_cumulative(SEXP r_0SEXP, SEXP c_0SEXP, SEXP k_1SEXP, SEXP k_2SEXP, SEXP k_3_initSEXP, SEXP k_3_slopeSEXP, SEXP timeSEXP, SEXP step_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type r_0(r_0SEXP);
    Rcpp::traits::input_parameter< double >::type c_0(c_0SEXP);
    Rcpp::traits::input_parameter< double >::type k_1(k_1SEXP);
    Rcpp::traits::input_parameter< double >::type k_2(k_2SEXP);
    Rcpp::traits::input_parameter< double >::type k_3_init(k_3_initSEXP);
    Rcpp::traits::input_parameter< double >::type k_3_slope(k_3_slopeSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lotka_volt_cumulative(r_0, c_0, k_1, k_2, k_3_init, k_3_slope, time, step_size));
    return rcpp_result_gen;
END_RCPP
}
// manager_frac
double manager_frac(const arma::vec& firm_vec, double span, int manage_rank_thresh);
RcppExport SEXP _hmod_manager_frac(SEXP firm_vecSEXP, SEXP spanSEXP, SEXP manage_rank_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type firm_vec(firm_vecSEXP);
    Rcpp::traits::input_parameter< double >::type span(spanSEXP);
    Rcpp::traits::input_parameter< int >::type manage_rank_thresh(manage_rank_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(manager_frac(firm_vec, span, manage_rank_thresh));
    return rcpp_result_gen;
END_RCPP
}
// model_beta
arma::mat model_beta(double a, double b, const arma::vec& base_emp_vec, const arma::uvec& emp_vec, const arma::vec& base_pay_vec, const arma::vec& beta_vec, double sigma, bool firm_size, bool hierarchy, bool power);
RcppExport SEXP _hmod_model_beta(SEXP aSEXP, SEXP bSEXP, SEXP base_emp_vecSEXP, SEXP emp_vecSEXP, SEXP base_pay_vecSEXP, SEXP beta_vecSEXP, SEXP sigmaSEXP, SEXP firm_sizeSEXP, SEXP hierarchySEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_emp_vec(base_emp_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type emp_vec(emp_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_pay_vec(base_pay_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type firm_size(firm_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type hierarchy(hierarchySEXP);
    Rcpp::traits::input_parameter< bool >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(model_beta(a, b, base_emp_vec, emp_vec, base_pay_vec, beta_vec, sigma, firm_size, hierarchy, power));
    return rcpp_result_gen;
END_RCPP
}
// model_r
arma::mat model_r(double a, double b, const arma::vec& base_emp_vec, const arma::uvec& emp_vec, const arma::vec& base_pay_vec, const arma::vec& r_vec, double sigma, bool firm_size, bool hierarchy, bool power);
RcppExport SEXP _hmod_model_r(SEXP aSEXP, SEXP bSEXP, SEXP base_emp_vecSEXP, SEXP emp_vecSEXP, SEXP base_pay_vecSEXP, SEXP r_vecSEXP, SEXP sigmaSEXP, SEXP firm_sizeSEXP, SEXP hierarchySEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_emp_vec(base_emp_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type emp_vec(emp_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type base_pay_vec(base_pay_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r_vec(r_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type firm_size(firm_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type hierarchy(hierarchySEXP);
    Rcpp::traits::input_parameter< bool >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(model_r(a, b, base_emp_vec, emp_vec, base_pay_vec, r_vec, sigma, firm_size, hierarchy, power));
    return rcpp_result_gen;
END_RCPP
}
// prod_curve
std::map< std::string, std::list<double>> prod_curve(const arma::uvec& well_id, const arma::vec& prod_first_6, const arma::vec& prod_first_12, const arma::vec& prod_first_24, const arma::vec& prod_first_60, const arma::vec& prod_last_year, const arma::vec& prod_daily_last_year, const arma::vec& prod_cumulative, const arma::vec& prod_peak_daily, const arma::vec& date_start, const arma::vec& date_end, const arma::vec& peak_month, const arma::vec& decline_3, const arma::vec& decline_12, const arma::vec& decline_24, const arma::vec& decline_60);
RcppExport SEXP _hmod_prod_curve(SEXP well_idSEXP, SEXP prod_first_6SEXP, SEXP prod_first_12SEXP, SEXP prod_first_24SEXP, SEXP prod_first_60SEXP, SEXP prod_last_yearSEXP, SEXP prod_daily_last_yearSEXP, SEXP prod_cumulativeSEXP, SEXP prod_peak_dailySEXP, SEXP date_startSEXP, SEXP date_endSEXP, SEXP peak_monthSEXP, SEXP decline_3SEXP, SEXP decline_12SEXP, SEXP decline_24SEXP, SEXP decline_60SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type well_id(well_idSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_first_6(prod_first_6SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_first_12(prod_first_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_first_24(prod_first_24SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_first_60(prod_first_60SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_last_year(prod_last_yearSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_daily_last_year(prod_daily_last_yearSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_cumulative(prod_cumulativeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prod_peak_daily(prod_peak_dailySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type date_start(date_startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type date_end(date_endSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type peak_month(peak_monthSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type decline_3(decline_3SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type decline_12(decline_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type decline_24(decline_24SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type decline_60(decline_60SEXP);
    rcpp_result_gen = Rcpp::wrap(prod_curve(well_id, prod_first_6, prod_first_12, prod_first_24, prod_first_60, prod_last_year, prod_daily_last_year, prod_cumulative, prod_peak_daily, date_start, date_end, peak_month, decline_3, decline_12, decline_24, decline_60));
    return rcpp_result_gen;
END_RCPP
}
// project
arma::mat project(arma::mat a, arma::vec c, arma::vec theta, arma::vec e);
RcppExport SEXP _hmod_project(SEXP aSEXP, SEXP cSEXP, SEXP thetaSEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(project(a, c, theta, e));
    return rcpp_result_gen;
END_RCPP
}
// read_column
std::vector<std::string> read_column(std::string filename, int col_number, std::string delimiter);
RcppExport SEXP _hmod_read_column(SEXP filenameSEXP, SEXP col_numberSEXP, SEXP delimiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type col_number(col_numberSEXP);
    Rcpp::traits::input_parameter< std::string >::type delimiter(delimiterSEXP);
    rcpp_result_gen = Rcpp::wrap(read_column(filename, col_number, delimiter));
    return rcpp_result_gen;
END_RCPP
}
// rpld
Rcpp::NumericVector rpld(int n, int xmin, double alpha, int discrete_max, int xmax, bool ordered);
RcppExport SEXP _hmod_rpld(SEXP nSEXP, SEXP xminSEXP, SEXP alphaSEXP, SEXP discrete_maxSEXP, SEXP xmaxSEXP, SEXP orderedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type discrete_max(discrete_maxSEXP);
    Rcpp::traits::input_parameter< int >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< bool >::type ordered(orderedSEXP);
    rcpp_result_gen = Rcpp::wrap(rpld(n, xmin, alpha, discrete_max, xmax, ordered));
    return rcpp_result_gen;
END_RCPP
}
// string_replace
std::vector<std::string> string_replace(std::vector<std::string> original, std::vector<std::string> replacement, std::vector<std::string> input_string);
RcppExport SEXP _hmod_string_replace(SEXP originalSEXP, SEXP replacementSEXP, SEXP input_stringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type original(originalSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type input_string(input_stringSEXP);
    rcpp_result_gen = Rcpp::wrap(string_replace(original, replacement, input_string));
    return rcpp_result_gen;
END_RCPP
}
// top_frac
double top_frac(arma::vec pay, double frac);
RcppExport SEXP _hmod_top_frac(SEXP paySEXP, SEXP fracSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pay(paySEXP);
    Rcpp::traits::input_parameter< double >::type frac(fracSEXP);
    rcpp_result_gen = Rcpp::wrap(top_frac(pay, frac));
    return rcpp_result_gen;
END_RCPP
}
// top_k
arma::rowvec top_k(const arma::vec& sort_vec, const arma::vec& data_vec, int k);
RcppExport SEXP _hmod_top_k(SEXP sort_vecSEXP, SEXP data_vecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type sort_vec(sort_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type data_vec(data_vecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(top_k(sort_vec, data_vec, k));
    return rcpp_result_gen;
END_RCPP
}
// weighted_mean
double weighted_mean(arma::vec x, arma::vec weights);
RcppExport SEXP _hmod_weighted_mean(SEXP xSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_mean(x, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hmod_base_fit", (DL_FUNC) &_hmod_base_fit, 3},
    {"_hmod_base_pay_sim", (DL_FUNC) &_hmod_base_pay_sim, 2},
    {"_hmod_base_pay_sim_beta", (DL_FUNC) &_hmod_base_pay_sim_beta, 3},
    {"_hmod_beta_sim_linear", (DL_FUNC) &_hmod_beta_sim_linear, 4},
    {"_hmod_beta_sim_log", (DL_FUNC) &_hmod_beta_sim_log, 4},
    {"_hmod_boot_mean", (DL_FUNC) &_hmod_boot_mean, 3},
    {"_hmod_boot_sigma", (DL_FUNC) &_hmod_boot_sigma, 1},
    {"_hmod_boot_span", (DL_FUNC) &_hmod_boot_span, 2},
    {"_hmod_ceo_pay_ratio", (DL_FUNC) &_hmod_ceo_pay_ratio, 6},
    {"_hmod_firm_grid", (DL_FUNC) &_hmod_firm_grid, 2},
    {"_hmod_firm_mean_pay", (DL_FUNC) &_hmod_firm_mean_pay, 6},
    {"_hmod_fit_beta", (DL_FUNC) &_hmod_fit_beta, 9},
    {"_hmod_fit_r", (DL_FUNC) &_hmod_fit_r, 7},
    {"_hmod_get_data", (DL_FUNC) &_hmod_get_data, 2},
    {"_hmod_get_ngrams", (DL_FUNC) &_hmod_get_ngrams, 1},
    {"_hmod_gini", (DL_FUNC) &_hmod_gini, 2},
    {"_hmod_grc", (DL_FUNC) &_hmod_grc, 1},
    {"_hmod_grid_plot_beta", (DL_FUNC) &_hmod_grid_plot_beta, 8},
    {"_hmod_grid_plot_r", (DL_FUNC) &_hmod_grid_plot_r, 7},
    {"_hmod_hierarchical_power", (DL_FUNC) &_hmod_hierarchical_power, 1},
    {"_hmod_hierarchy", (DL_FUNC) &_hmod_hierarchy, 2},
    {"_hmod_hp_mod", (DL_FUNC) &_hmod_hp_mod, 2},
    {"_hmod_k_function", (DL_FUNC) &_hmod_k_function, 3},
    {"_hmod_lorenz", (DL_FUNC) &_hmod_lorenz, 4},
    {"_hmod_lotka_volt", (DL_FUNC) &_hmod_lotka_volt, 7},
    {"_hmod_lotka_volt_cumulative", (DL_FUNC) &_hmod_lotka_volt_cumulative, 8},
    {"_hmod_manager_frac", (DL_FUNC) &_hmod_manager_frac, 3},
    {"_hmod_model_beta", (DL_FUNC) &_hmod_model_beta, 10},
    {"_hmod_model_r", (DL_FUNC) &_hmod_model_r, 10},
    {"_hmod_prod_curve", (DL_FUNC) &_hmod_prod_curve, 16},
    {"_hmod_project", (DL_FUNC) &_hmod_project, 4},
    {"_hmod_read_column", (DL_FUNC) &_hmod_read_column, 3},
    {"_hmod_rpld", (DL_FUNC) &_hmod_rpld, 6},
    {"_hmod_string_replace", (DL_FUNC) &_hmod_string_replace, 3},
    {"_hmod_top_frac", (DL_FUNC) &_hmod_top_frac, 2},
    {"_hmod_top_k", (DL_FUNC) &_hmod_top_k, 3},
    {"_hmod_weighted_mean", (DL_FUNC) &_hmod_weighted_mean, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hmod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
