# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

base_fit <- function(a, b, emp_vec) {
    .Call('_hmod_base_fit', PACKAGE = 'hmod', a, b, emp_vec)
}

base_pay_sim <- function(base_pay_empirical, n_sim) {
    .Call('_hmod_base_pay_sim', PACKAGE = 'hmod', base_pay_empirical, n_sim)
}

base_pay_sim_beta <- function(base_pay_empirical, beta_empirical, beta_simulated) {
    .Call('_hmod_base_pay_sim_beta', PACKAGE = 'hmod', base_pay_empirical, beta_empirical, beta_simulated)
}

beta_sim_linear <- function(employment, beta, sim_employment, bin_factor) {
    .Call('_hmod_beta_sim_linear', PACKAGE = 'hmod', employment, beta, sim_employment, bin_factor)
}

beta_sim_log <- function(employment, beta, sim_employment, bin_factor) {
    .Call('_hmod_beta_sim_log', PACKAGE = 'hmod', employment, beta, sim_employment, bin_factor)
}

boot_mean <- function(x, conf, n_boot) {
    .Call('_hmod_boot_mean', PACKAGE = 'hmod', x, conf, n_boot)
}

boot_sigma <- function(x) {
    .Call('_hmod_boot_sigma', PACKAGE = 'hmod', x)
}

boot_span <- function(h, s) {
    .Call('_hmod_boot_span', PACKAGE = 'hmod', h, s)
}

ceo_pay_ratio <- function(a, b, base_employment_vec, total_employment_vec, base_pay_vec, beta_vec) {
    .Call('_hmod_ceo_pay_ratio', PACKAGE = 'hmod', a, b, base_employment_vec, total_employment_vec, base_pay_vec, beta_vec)
}

firm_grid <- function(base_vec, stretch) {
    .Call('_hmod_firm_grid', PACKAGE = 'hmod', base_vec, stretch)
}

firm_mean_pay <- function(a, b, base_employment_vec, total_employment_vec, base_pay_vec, beta_vec) {
    .Call('_hmod_firm_mean_pay', PACKAGE = 'hmod', a, b, base_employment_vec, total_employment_vec, base_pay_vec, beta_vec)
}

fit_beta <- function(a, b, base_employment_vec, total_employment_vec, ceo_ratio_vec, firm_mean_pay_vec, ceo_ratio_error_tolerance, min_beta, max_beta) {
    .Call('_hmod_fit_beta', PACKAGE = 'hmod', a, b, base_employment_vec, total_employment_vec, ceo_ratio_vec, firm_mean_pay_vec, ceo_ratio_error_tolerance, min_beta, max_beta)
}

fit_r <- function(a, b, base_emp_vec, emp_vec, c_r_vec, m_pay_vec, tol) {
    .Call('_hmod_fit_r', PACKAGE = 'hmod', a, b, base_emp_vec, emp_vec, c_r_vec, m_pay_vec, tol)
}

get_data <- function(filename, ids) {
    .Call('_hmod_get_data', PACKAGE = 'hmod', filename, ids)
}

get_words <- function(filename) {
    .Call('_hmod_get_words', PACKAGE = 'hmod', filename)
}

gini <- function(x, corr = FALSE) {
    .Call('_hmod_gini', PACKAGE = 'hmod', x, corr)
}

grc <- function(n_subordinates) {
    .Call('_hmod_grc', PACKAGE = 'hmod', n_subordinates)
}

grid_plot_beta <- function(a, b, sigma, firm_grid, emp_vec, base_vec, base_pay_vec, beta_vec) {
    .Call('_hmod_grid_plot_beta', PACKAGE = 'hmod', a, b, sigma, firm_grid, emp_vec, base_vec, base_pay_vec, beta_vec)
}

grid_plot_r <- function(a, b, sigma, firm_grid, base_vec, base_pay_vec, r_vec) {
    .Call('_hmod_grid_plot_r', PACKAGE = 'hmod', a, b, sigma, firm_grid, base_vec, base_pay_vec, r_vec)
}

hierarchical_power <- function(hierarchy_vec) {
    .Call('_hmod_hierarchical_power', PACKAGE = 'hmod', hierarchy_vec)
}

hierarchy <- function(firm_size, span_of_control) {
    .Call('_hmod_hierarchy', PACKAGE = 'hmod', firm_size, span_of_control)
}

hp_mod <- function(firm_vec, span) {
    .Call('_hmod_hp_mod', PACKAGE = 'hmod', firm_vec, span)
}

k_function <- function(pay, power, k_parameters) {
    .Call('_hmod_k_function', PACKAGE = 'hmod', pay, power, k_parameters)
}

lorenz <- function(pay, lower, upper, n_bins) {
    .Call('_hmod_lorenz', PACKAGE = 'hmod', pay, lower, upper, n_bins)
}

manager_frac <- function(firm_vec, span, manage_rank_thresh) {
    .Call('_hmod_manager_frac', PACKAGE = 'hmod', firm_vec, span, manage_rank_thresh)
}

model_beta <- function(a, b, base_emp_vec, emp_vec, base_pay_vec, beta_vec, sigma, firm_size = FALSE, hierarchy = FALSE, power = FALSE) {
    .Call('_hmod_model_beta', PACKAGE = 'hmod', a, b, base_emp_vec, emp_vec, base_pay_vec, beta_vec, sigma, firm_size, hierarchy, power)
}

model_r <- function(a, b, base_emp_vec, emp_vec, base_pay_vec, r_vec, sigma, firm_size = FALSE, hierarchy = FALSE, power = FALSE) {
    .Call('_hmod_model_r', PACKAGE = 'hmod', a, b, base_emp_vec, emp_vec, base_pay_vec, r_vec, sigma, firm_size, hierarchy, power)
}

project <- function(a, c, theta, e) {
    .Call('_hmod_project', PACKAGE = 'hmod', a, c, theta, e)
}

rpld <- function(n, xmin, alpha, discrete_max = 10000L, xmax = 0L, ordered = FALSE) {
    .Call('_hmod_rpld', PACKAGE = 'hmod', n, xmin, alpha, discrete_max, xmax, ordered)
}

string_replace <- function(original, replacement, input_string) {
    .Call('_hmod_string_replace', PACKAGE = 'hmod', original, replacement, input_string)
}

top_frac <- function(pay, frac) {
    .Call('_hmod_top_frac', PACKAGE = 'hmod', pay, frac)
}

top_k <- function(sort_vec, data_vec, k) {
    .Call('_hmod_top_k', PACKAGE = 'hmod', sort_vec, data_vec, k)
}

weighted_mean <- function(x, weights) {
    .Call('_hmod_weighted_mean', PACKAGE = 'hmod', x, weights)
}

